inventory/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'inventory'
urlpatterns = [
    path('', views.index, name='index'),
    path('locations/', views.LocationsView.as_view(), name='locations'),
    path('location/<int:pk>/', views.LocationView.as_view(), name='location'),
    path('location/<int:pk>/new/', views.location_new, name='locationnew'),
    path('location/<int:pk>/newmulti/', views.location_new_multiple, name='locationnewmulti'),
    path('location/<int:pk>/edit/', views.location_edit, name='locationedit'),
    path('location/<int:pk>/trash/', views.location_trash, name='locationtrash'),
    path('location/<int:pk>/untrash/', views.location_untrash, name='locationuntrash'),
    path('location/<int:pk>/delete/', views.location_delete, name='locationdelete'),
    path('location/<int:pk>/uuid/', views.location_edit_uuid, name='locationedituuid'),
    path('location/find/', views.location_find, name='locationfind'),
    path('location/find/<uuid:id>/', views.location_find_uuid, name='locationfinduuid'),
    path('location/<int:pk>/newitem/', views.item_new, name='locationnewitem'),
    path('location/findfreeslot/', views.LocationFindFreeSlot.as_view(), name='locationfindfreeslot'),
    path('categories/', views.CategoriesView.as_view(), name='categories'),
    path('category/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('category/<int:pk>/new/', views.category_new, name='categorynew'),
    path('category/<int:pk>/edit/', views.category_edit, name='categoryedit'),
    path('category/<int:pk>/trash/', views.category_trash, name='categorytrash'),
    path('category/<int:pk>/untrash/', views.category_untrash, name='categoryuntrash'),
    path('category/<int:pk>/delete/', views.category_delete, name='categorydelete'),
    path('item/<int:pk>/', views.ItemView.as_view(), name='item'),
    path('item/<int:pk>/trash/', views.item_trash, name='itemtrash'),
    path('item/<int:pk>/untrash/', views.item_untrash, name='itemuntrash'),
    path('item/<int:pk>/delete/', views.item_delete, name='itemdelete'),
    path('item/<int:pk>/edit/', views.item_edit, name='itemedit'),
    path('item/<int:pk>/lend/', views.item_lend, name='itemlend'),
    path('item/<int:pk>/returno/)', views.item_return, name='itemreturn'),
    path('search/', views.SearchItem.as_view(), name='search'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='inventory/landing.html'), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/', views.AccountsProfile.as_view(), name='profile'),
    path('accounts/print_list/', views.print_list, name='print_list'),
    path('accounts/print_list/clear/', views.print_list_clear, name='print_list_clear'),
    path('accounts/print_list/add/<int:pk>', views.print_list_add, name='print_list_add'),
    path('accounts/print_list/remove/<int:pk>', views.print_list_remove, name='print_list_remove'),
    path('trash/', views.TrashView.as_view(), name='trash'),
]

inventorymanager/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('inventory.urls')),
    path('admin/', admin.site.urls),
]

inventory/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from mptt.models import MPTTModel, TreeForeignKey
from django.utils.translation import gettext as _
from django.contrib.auth.models import User

ITEM_STATES = (
    ('d', 'default'),
    ('t', 'trashed'),
    ('a', 'archived'),
)

class Location(MPTTModel):
    name = models.CharField(verbose_name=_("Name"), max_length=200)
    creation_date = models.DateTimeField(verbose_name=_("Creation date"), default=timezone.now)
    change_date = models.DateTimeField(verbose_name=_("Change date"), auto_now=True)
    parent =  TreeForeignKey('self', on_delete=models.CASCADE, null=True, related_name='children', verbose_name=_("Parent"))
    free_space = models.BooleanField(verbose_name=_("Free space"), default=True)
    uuid = models.UUIDField(verbose_name=_("UUID"), null=True, blank=True)
    description = models.CharField(verbose_name=_("Description"), max_length=1000)
    state = models.CharField(verbose_name=_("State"), max_length=1, choices=ITEM_STATES, default="d")

    def __str__(self):
        return self.name

    class Meta:
        permissions = [
            ('trash_location', 'Can trash location')
        ]

class LocationPrintList(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    locations = models.ManyToManyField(Location)

    def for_user(user):
        return LocationPrintList.objects.get(user=user).locations
    

class Category(MPTTModel):
    name = models.CharField(max_length=200, verbose_name=_("Name"))
    creation_date = models.DateTimeField(default=timezone.now, verbose_name=_("Creation Date"))
    change_date = models.DateTimeField(auto_now=True, verbose_name=_("Change Date"))
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, related_name='children', verbose_name=_("Supercategory"))
    description = models.CharField(max_length=1000, verbose_name=_("Description"))
    state = models.CharField(max_length=1, choices=ITEM_STATES, default="d", verbose_name=_("State"))

    def __str__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name_plural = _("Categories")
        permissions = [
            ('trash_category', 'Can trash category')
        ]


class Item(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("Name"))
    creation_date = models.DateTimeField(default=timezone.now, verbose_name=_("Creation Date"))
    change_date = models.DateTimeField(auto_now=True, verbose_name=_("Change Date"))
    location = TreeForeignKey(Location, on_delete=models.CASCADE, null=True, verbose_name=_("Location"))
    amount = models.IntegerField(default=1, validators=[MinValueValidator(0)], verbose_name=_("Amount"))
    description = models.CharField(max_length=1000, verbose_name=_("Description"))
    category = TreeForeignKey(Category, on_delete=models.CASCADE, null=True, verbose_name=_("Category"))
    barcode = models.BigIntegerField(blank=True, null=True, verbose_name=_("Barcode"))
    lent = models.BooleanField(default=False, verbose_name=_("lent"))
    lent_to = models.CharField(max_length=100, default="", verbose_name=_("Lent to"))
    lent_date = models.DateTimeField(null=True, verbose_name=_("Lent Date"))
    state = models.CharField(max_length=1, choices=ITEM_STATES, default="d", verbose_name=_("State"))

    def __str__(self):
        return self.name

    class Meta:
        permissions = [
            ('trash_item', 'Can trash item'),
            ('lend_item', 'Can lend item'),
        ]
    

inventory/forms.py
from django import forms
from django.utils.translation import gettext as _

from .models import Item, Location, Category

class ItemEditForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = ['name', 'description', 'amount', 'location', 'category', 'barcode']
        labels = {
            'name': _("Name"),
            'description': _("Description"),
            'amount': _("Amount"),
            'location': _("Location"),
            'category': _("Category"),
            'barcode': _("Barcode"),
        }


class ItemLendForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = ['lent_to']

        
class LocationEditForm(forms.ModelForm):

    class Meta:
        model = Location
        fields = ['name', 'description', 'parent']


class CategoryEditForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ['name', 'description', 'parent']

class LocationUuidEditForm(forms.ModelForm):

    class Meta:
        model = Location
        fields = ['uuid']

inventory/views.py
import logging
from django.utils.datastructures import MultiValueDictKeyError
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.translation import gettext as _
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin

from uuid import UUID

from .models import Item, Location, Category, LocationPrintList
from .forms import LocationEditForm, ItemEditForm, ItemLendForm, CategoryEditForm, LocationUuidEditForm

logger = logging.getLogger(__name__)

types = ['item', 'category', 'location']

@permission_required('inventory.view_item')
@permission_required('inventory.view_location')
@permission_required('inventory.view_category')
def index(request):
    latest_items = Item.objects.order_by('-creation_date')[:5]
    categories = Category.objects.order_by('-creation_date')[:5]
    locations = Location.objects.order_by('-creation_date')[:5]
    return render(request, 'inventory/index.html', {
        'title': 'Home',
        'latest_items': latest_items,
        'categories': categories,
        'locations': locations,
        'nav_item': _("Home"),
    })

class SearchItem(PermissionRequiredMixin, generic.ListView):
    permission_required = ('inventory.view_item', 'inventory.view_location','inventory.view_category')
    paginate_by = 25
    template_name = 'inventory/search.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_term'] = self.request.GET['q']
        if self.request.GET['type'] in types:
            context['search_type'] = self.request.GET['type']
        else:
            context['search_type'] = types[0]
        if len(context['search_term']) < 3:
            context['error_message'] = _("Search term must contain at least 3 letters.")
        context['title'] = _("Search")
        return context
    
    def get_queryset(self):
        search_term = self.request.GET['q']
        search_type = self.request.GET['type']
        if len(search_term) < 3:
            return []
        else:
            if search_type == 'item':
                results = Item.objects.filter(name__icontains=search_term).order_by('name')
            elif search_type == 'location':
                results = Location.objects.filter(name__icontains=search_term).order_by('name')
            elif search_type == 'category':
                results = Category.objects.filter(name__icontains=search_term).order_by('name')
            else:
                results = []
            return results

class LocationsView(PermissionRequiredMixin, generic.ListView):
    permission_required = ('inventory.view_location')
    model = Location
    paginate_by = 25

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _("Locations")
        return context

    def get_queryset(self):
        return Location.objects.filter(state__exact='d')
    

class CategoriesView(PermissionRequiredMixin, generic.ListView):
    permission_required = ('inventory.view_category')
    model = Category
    paginate_by = 25

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _("Categories")
        return context

class LocationView(PermissionRequiredMixin, generic.ListView):
    permission_required = ('inventory.view_item', 'inventory.view_location','inventory.view_category')
    model = Item
    template_name = 'inventory/location_detail.html'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        location = Location.objects.get(pk=kwargs['pk'])
        self.object_list = Item.objects.filter(location__exact=location, state__exact='d').order_by('name')

        context = self.get_context_data()
        context['location'] = location
        context['location_list'] = location.get_descendants().filter(state__exact='d')
        context['title'] = _("Location")
        return self.render_to_response(context)

    
class CategoryView(PermissionRequiredMixin, generic.ListView):
    permission_required = ('inventory.view_item', 'inventory.view_location', 'inventory.view_category')
    model = Item
    template_name = 'inventory/category_detail.html'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        category = Category.objects.get(pk=kwargs['pk'])
        self.object_list = Item.objects.filter(category__exact=category, state__exact='d')

        context = self.get_context_data()
        context['category'] = category
        context['subcategories'] = category.get_descendants().filter(state__exact='d')
        context['title'] = _("Category")
        return self.render_to_response(context)


class ItemView(PermissionRequiredMixin, generic.DetailView):
    permission_required = ('inventory.view_item')
    model = Item

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _("Item")
        return context

@permission_required('inventory.edit_location')
def location_edit_uuid(request, pk):
    location = get_object_or_404(Location, pk=pk)
    if request.method == 'POST':
        form = LocationUuidEditForm(request.POST, instance=location)
        
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('inventory:location', args=(location.pk,)))
    else:
        form = LocationUuidEditForm(instance=location)

    return render(request, 'inventory/location_edit_uuid.html', {
        'title': _("Edit Location"),
        'form': form,
        'location': location,
    })

@permission_required('inventory.view_location')
def location_find(request):
    if 'uuid' in request.GET:
        uuid = request.GET['uuid']
        return HttpResponseRedirect(reverse('inventory:locationfinduuid', args=(uuid,)))
    
    return render(request, 'inventory/location_find.html', {
    })


class LocationFindFreeSlot(PermissionRequiredMixin, generic.ListView):
    permission_required = ('inventory.view_item', 'inventory.view_location', 'inventory.view_category')
    model = Location
    paginate_by = 25
    template_name = 'inventory/location_findfreeslot.html'

    def get_queryset(self):
        locations = Location.objects.filter(free_space__exact=True)
        return locations

@permission_required('inventory.view_location')
def location_find_uuid(request, id):
    location = get_object_or_404(Location, uuid=id)
    return render(request, 'inventory/location_detail.html', {
        'title': _("Find location"),
        'location': location,
    })

@permission_required('inventory.view_location')
@permission_required('inventory.view_category')
@permission_required('inventory.add_item')
def item_new(request, pk):
    location = get_object_or_404(Location, pk=pk)
    category = Category.objects.get(pk=1)
    if request.method == 'POST':
        form = ItemEditForm(request.POST)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('inventory:location', args=(pk,)))

    else:
        item = Item(location=location, category=category)
        form = ItemEditForm(instance=item)

    return render(request, 'inventory/item_new.html', {
        'title': _("New item"),
        'form': form,
        'location': location,
    })

@permission_required('inventory.view_item')
@permission_required('inventory.view_item')
def item_edit(request, pk):
    instance = get_object_or_404(Item, pk=pk)
    if request.method == 'POST':
        form = ItemEditForm(request.POST or None, instance=instance)

        if form.is_valid():
            instance = form.save()
            return HttpResponseRedirect(reverse('inventory:location', args=(instance.location.pk,)))

    else:
        form = ItemEditForm(instance=instance)

    return render(request, 'inventory/item_edit.html', {
        'title': _("Edit item"),
        'form': form,
        'instance': instance,
    })

@permission_required('inventory.delete_item')
def item_delete(request, pk):
    item = get_object_or_404(Item, pk=pk)
    if item.state != 't':
        raise Http404("Item must be trashed first.")
    item.delete()

    return HttpResponseRedirect(reverse('inventory:trash'))

@permission_required('inventory.trash_item')
def item_trash(request, pk):
    item = get_object_or_404(Item, pk=pk)
    location = item.location
    item.state = 't'
    item.save()

    return HttpResponseRedirect(reverse('inventory:location', args=(location.pk,)))

@permission_required('inventory.trash_item')
def item_untrash(request, pk):
    item = get_object_or_404(Item, pk=pk)
    if item.state != 't':
        raise Http404(_("Cannot untrash non-trashed item"))
    item.state = 'd'
    item.save()

    return HttpResponseRedirect(reverse('inventory:trash', args=()))
    
@permission_required('inventory.lend_item')
def item_lend(request, pk):
    instance = get_object_or_404(Item, pk=pk)

    if request.method == 'POST':
        form = ItemLendForm(request.POST or None, instance=instance)

        if form.is_valid():
            instance = form.save(commit=False)
            instance.lent = True
            instance.lent_date = timezone.now()
            instance.save()
            return HttpResponseRedirect(reverse('inventory:item', args=(instance.pk,)))

    else:
        form = ItemLendForm(instance=instance)

    return render(request, 'inventory/item_lend.html', {
        'title': _("Lend item"),
        'form': form,
        'instance': instance,
    })

def redirect_next(request, item, message):
    if 'next' in request:
        raise Http404(_("Missing argument"))

inventory/templates/inventory/back.html
{% load i18n %}
<a href="#" class="btn btn-primary" onclick="window.history.back()">{% trans "Back" %}</a>

inventory/templates/inventory/category_detail.html
{% extends 'inventory/base.html' %}
{% load i18n %}

{% block content %}
{% if error_message %}
<p class="alert alert-danger">
  {{ error_message }}
</p>
{% endif %}
<div class="row">
  <div class="col-auto">
    <h2>{{ category.name }}</h2>
    </div>
  <div class="col-auto">
    {% include 'inventory/category_actions.html' %}
  </div>
</div>
{% include 'inventory/breadcrumbs.html' with root=category reflink='inventory:category' %}
<p></p>
<table class="table table-striped">
  <tr>
    <th><span class="material-icons">description</span>{% trans "Description" %}</th>
    <td>{{ category.description }}</td>
  </tr>
</table>
<h2>{% trans "Items" %}</h2>
{% include 'inventory/item_list.html' with list=item_list next='category' %}
<div class="row">
  <div class="col-auto">
    <h2>{% trans "Subcategories" %}</h2>
  </div>
  <div class="col-auto">
    <a href="{% url 'inventory:categorynew' category.pk %}" class="btn btn-sm btn-outline-primary material-icons">add</a>
  </div>
</div>
{% include 'inventory/category_list_atom.html' with category_list=subcategories %}
<p></p>
{% include 'inventory/back.html' %}
{% endblock %}

inventory/templates/inventory/category_new.html
{% extends 'inventory/base.html' %}
{% load i18n %}

{% block content %}
<h1>{% trans "New Category" %}</h1>
<form class="form" method="post" action="{% url 'inventory:categorynew' instance.parent.pk %}">
  {% csrf_token %}
  {% include 'inventory/form.html' %}
  <div class="form-row">
    <div class="col-auto">
      <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
    </div>
    <div class="col-auto">
      <input type="button" class="btn" onclick="window.history.back()" value="{% trans "Cancel" %}" />
    </div>
  </div>
</form>
{% endblock %}

inventory/templates/inventory/index.html
{% extends 'inventory/base.html' %}
{% load i18n %}

{% block content %}
<div class="row mb-4">
  <div class="col">
    <h2>{% trans "Latest Items" %}</h2>
    <div class="table-responsive">
      <table class="table table-hover table-sm">
        <thead>
          <tr>
            <th><span class="material-icons">bar_chart</span></th>
            <th><span class="material-icons">label</span>{% trans "Name" %}</th>
            <th><span class="material-icons">archive</span>{% trans "Location" %}</th>
            <th><span class="material-icons">category</span>{% trans "Category" %}</th>
            <th class="d-none d-md-table-cell">
              <span class="material-icons">create</span>
              {% trans "Created" %}
            </th>
          </tr>
        </thead>
        {% for item in latest_items %}
        <tr>
          <td>{{ item.amount }}</td>
          <td><a href="{% url 'inventory:item' item.pk %}">{{ item.name }}</a></td>
          <td><a href="{% url 'inventory:location' item.location.pk %}">{{ item.location }}</a></td>
          <td><a href="{% url 'inventory:category' item.category.pk %}">{{ item.category }}</a></td>
          <td class="d-none d-md-table-cell">{{ item.creation_date|date:'d. M. H:i' }}</td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-12 col-lg-5 mb-4">
    <h2>{% trans "Latest Categories" %}</h2>
    <table class="table table-hover table-sm">
      <thead>
        <tr>
          <th><span class="material-icons">label</span>{% trans "Name" %}</th>
          <th><span class="material-icons">create</span>{% trans "Created" %}</th>
        </tr>
      </thead>
      {% for category in categories %}
      <tr>
        <td><a href="{% url 'inventory:category' category.pk %}">{{ category.name }}</a></td>
        <td>{{ category.creation_date|date:'d. M. H:i' }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>
  <div class="col-lg-1"></div>
  <div class="col">
    <h2>{% trans "Latest Locations" %}</h2>
    <table class="table table-hover table-sm">
      <thead>
        <tr>
          <th><span class="material-icons">label</span>{% trans "Name" %}</th>
          <th><span class="material-icons">create</span>{% trans "Created" %}</th>
        </tr>
      </thead>
      {% for location in locations %}
      <tr>
        <td><a href="{% url 'inventory:location' location.pk %}">{{ location.name }}</a></td>
        <td>{{ location.creation_date|date:'d. M. H:i' }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>

  {% endblock %}

inventory/templates/inventory/item_lend.html
{% extends 'inventory/base.html' %}
{% load i18n %}

{% block content %}
<h1>{% trans "Lend Item" %}</h1>
<form class="form" method="post" action="{% url 'inventory:itemlend' instance.pk %}">
  {% csrf_token %}
  {% include 'inventory/form.html' %}
  <div class="form-row">
    <div class="col-auto">
      <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
    </div>
    <div class="col-auto">
      <input type="button" class="btn" onclick="window.history.back()" value="{% trans "Cancel" %}" />
    </div>
  </div>
</form>
{% endblock %}

inventory/templates/inventory/landing.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>{% trans "Inventory Manager - Sign In" %}</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static 'landing_style.css' %}" rel="stylesheet">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/favicon-16x16.png">
    <link rel="shortcut icon" href="/static/favicon.ico">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <style>
      .errorlist {
          list-style: none;
          margin: 0;
          padding: 0;
      }
    </style>
  </head>
  <body class="text-center">
    <form class="form-signin" method="post" action="{% url 'inventory:login' %}">
      {% csrf_token %}
      <img class="mb-4" src="{% static 'apple-touch-icon.png' %}" alt="LOGO" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">{% trans "Please sign in" %}</h1>
      <div class="form-group">
      <label for="{{ form.username.id_for_label }}" class="sr-only">{{ form.username.label }}</label>
      <input type="text" name="{{ form.username.html_name }}" autofocus autocapitalize="none" autocomplete="username" maxlength="150" class="form-control{% if form.username.errors %} is-invalid{% endif %}" required id="{{ form.username.id_for_label }}" placeholder="{{ form.username.label }}" value="">
      <label for="{{ form.password.id_for_label }}" class="sr-only">{{ form.password.label }}</label>
      <input type="password" name="{{ form.password.html_name }}" autocomplete="current-password" class="form-control{% if form.password.errors %} is-invalid{% endif %}" required id="{{ form.password.id_for_label }}" placeholder="{{ form.password.label }}">
      <input type="hidden" name="next" value="{{ next }}">
      <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans "Sign in" %}</button>
      </div>
      {% if form.non_field_errors %}
      <div class="alert alert-danger">
        {% trans "Your username and password didn't match. Please try again." %}
      </div>
      {% endif %}
      <p class="mt-5 mb-3 text-muted">{% trans "Inventory Manager" %} v1.0</p>
    </form>
  </body>
</html>

inventory/templates/inventory/location_edit.html
{% extends 'inventory/base.html' %}
{% load i18n %}

{% block content %}
<h1>{% trans 'Edit Location' %}</h1>
<form class="form" method="post" action="{% url 'inventory:locationedit' instance.pk %}">
  {% csrf_token %}
  {% include 'inventory/form.html' %}
  <div class="form-row">
    <div class="col-auto">
      <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
    </div>
    <div class="col-auto">
      <input type="button" class="btn" onclick="window.history.back()" value="Cancel" />
    </div>
  </div>
</form>
{% endblock %}

inventory/templates/inventory/location_find.html
{% extends 'inventory/base.html' %}
{% load i18n %}

{% block content %}
<h1>{% trans "Find location" %}</h1>
<form action="{% url 'inventory:locationfind' %}" type="get">
  <div class="form-group">
    <label for="id_uuid">{% trans "UUID" %}</label>
    <input type="text" placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" name="uuid" id="id_uuid" class="form-control">
  </div>
  <div class="form-group">
    <input type="submit" value="{% trans "Find" %}" class="btn btn-primary">
  </div>
</form>
{% endblock %}

inventory/templates/inventory/location_new_multiple.html
{% extends 'inventory/base.html' %}
{% load i18n %}

{% block content %}
<h1>{% trans "New Location (multiple)" %}</h1>
<form class="form" method="post" action="{% url 'inventory:locationnewmulti' instance.parent.pk %}">
  {% csrf_token %}
  {% include 'inventory/form.html' %}
  <div class="form-group">
    <label for="id_amount">{% trans 'Amount:' %}</label>
    <input name="amount" id="id_amount" type="number" class="form-control" value="2" />
  </div>
  <div class="form-row">
    <div class="col-auto">
      <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
    </div>
    <div class="col-auto">
      <input type="button" class="btn" onclick="window.history.back()" value="{% trans "Cancel" %}" />
    </div>
  </div>
</form>
{% endblock %}

inventory/templates/inventory/trash.html
{% extends 'inventory/base.html' %}
{% load i18n %}

{% block content %}
<h1>{% trans "Trash" %}</h1>
<form name="trashform">
  <div class="form-row">
    <div class="">
      <div class="form-group">
        <!--label>{% trans "Filter" %}:</label-->
        <div class="form-control">
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="type" id="id_item" value="item" {% if search_type == 'item' %}checked{% endif %} onchange="document.trashform.submit()">
            <label class="form-check-label" for="id_item">{% trans "Items" %}</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="type" id="id_location" value="location" {% if search_type == 'location' %}checked{% endif %} onchange="document.trashform.submit()">
            <label class="form-check-label" for="id_location">{% trans "Locations" %}</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="type" id="id_category" value="category"  {% if search_type == 'category' %}checked{% endif %} onchange="document.trashform.submit()">
            <label class="form-check-label" for="id_category">{% trans "Categories" %}</label>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% if search_type == 'item' %}
{% include 'inventory/item_list.html' with list=page_obj %}
{% elif search_type == 'location' %}
{% include 'inventory/location_list_atom.html' with location_list=page_obj %}
{% elif search_type == 'category' %}
{% include 'inventory/category_list_atom.html' with category_list=page_obj %}
{% endif %}
{% endblock %}